metrics_to_publish:
  common_process_uptime_second:
  soft_media_error_lower:
  soft_media_error_upper:
  power_cycle_lower:
  power_cycle_upper:
  power_on_hour_lower:
  power_on_hour_upper:
  unsafe_shutdowns_lower:
  unsafe_shutdowns_upper:
  temperature:
  available_spare:
  available_spare_threshold:
  percentage_used:
  controller_busy_time_lower:
  controller_busy_time_upper:
  warning_temperature_time:
  critical_temperature_time:
  read_iops_device:
  read_bps_device:
  write_iops_device:
  write_bps_device:
  read_iops_network:
  read_bps_network:
  write_iops_network:
  write_bps_network:
  array_capacity_total:
  array_usage_blk_cnt:
  array_status:
  volume_capacity_total:
  volume_usage_blk_cnt:
  volume_state:
  read_avg_lat_volume:
  read_iops_volume:
  read_bps_volume:
  write_avg_lat_volume:
  write_iops_volume:
  write_bps_volume:
  gc_stripe_count_requested:
  gc_stripe_count_completed:
  gc_stripe_count_flush_requested:
  gc_stripe_count_flush_completed:
  gc_stripe_count_map_update_requested:
  gc_stripe_count_map_update_completed:
  gc_stripe_count_force_flush_requested:
