
name: M8-72H_VM_Test

on:
  schedule:
    - cron: '0 16 * * MON-FRI'

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  Prepare_Dashboard_Link:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Dashboard link for workflow 
      run: |
        POS_WORKING_DIR=${{github.workspace}} GA_COMMIT_HASH=${{github.sha}} GA_WORKFLOW=${{github.workflow}} GRAFANA_DASHBOARD="${{secrets.GRAFANA_GITHUB_ACTION_DASHBAORD_LINK}}" bash ${{github.workspace}}/.github/workflows/script/setup_dashboard.sh
    - name: Upload Dashboard Link
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.workflow}}-Dashboard
        path: |
          ${{github.workspace}}/Dashboard.html

  Three_Days_Test:
    runs-on: VM
    timeout-minutes: 5000
    steps:
    
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: | 
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}} -c --with-fpic 

    - name: 72 Hour VM Test
      working-directory: ${{github.workspace}}
      run: |
        POS_WORKING_DIR=${{github.workspace}} GA_COMMIT_HASH=${{github.sha}} GA_WORKFLOW=${{github.workflow}} GA_DETAIL=NULL POS_EXPORTER_PORT=${{secrets.POS_EXPORTER_PORT}} AMP_REMOTE_WRITE_URL=${{secrets.AMP_REMOTE_WRITE_URL}} AMP_SIGV4_REGION=${{secrets.AMP_SIGV4_REGION}} AMP_SIGV4_ACCESS_KEY=${{secrets.AMP_SIGV4_ACCESS_KEY}} AMP_SIGV4_SECRET_KEY=${{secrets.AMP_SIGV4_SECRET_KEY}} bash ${{github.workspace}}/.github/workflows/script/setup_monitoring.sh
        chmod +x .github/workflows/script/72_hour.sh
        .github/workflows/script/72_hour.sh ${{github.workspace}}

    - name: Clean Backup Script
      continue-on-error: true
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/clean_backup.sh
        .github/workflows/script/clean_backup.sh -i "127.0.0.1" -p "M8-72H_VM_Test" -n "72h" -r ${{github.sha}} -d ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Three_Days_LOG
        path: |
          /var/log/pos

  Create_Issue:
    needs: Three_Days_Test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      id: create-issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DASHBOARD_URL: ${{ secrets.GRAFANA_GITHUB_ACTION_DASHBAORD_LINK }}&refresh=5s&var-ga_commit_hash=${{ github.sha }}&var-ga_workflow=${{ github.workflow }}
        ACTION_URL: https://github.com/poseidonos/poseidonos/actions/runs/${{ github.run_id }}
        WORKFLOW_NAME: ${{ github.workflow }}
        RUN_NUMBER: ${{ github.run_number }}
        ACTOR: ${{ github.actor }}
        SHA_URL: https://github.com/poseidonos/poseidonos/commit/${{ github.sha }}
      with:
        assignees: ${{github.actor}} 

    - name: Make and Annotate Dashboard Link for Workflow
      run: |
        echo "::notice title=Go to Issue & Check Dashboard::Issue #${{ steps.create-issue.outputs.number }} is created for these jobs : ${{ steps.create-issue.outputs.url }}"