
name: R4-Coverage_VM_Test

on:
  schedule:
    - cron: '0 4-21/3 * * MON-FRI'

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  check_date:
    runs-on: VM
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
         ref: release/v0.12.0

    - id: should_run
      name: check latest commit is less than 3 hours
      if: ${{ github.event_name == 'schedule' }}
      working-directory: ${{github.workspace}}
      run: 
        date=`date -d "-3 hours" "+%s"`; result=`git rev-list -1 --after=$date main`
        test -z $result && echo "::set-output name=should_run::false"
  
  Prepare_Dashboard_Link:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
         ref: release/v0.12.0

    - name: Make Monitoring Dashboard Link
      uses: ./.github/actions/make-monitoring-dashboard-link
      with:
        GRAFANA_DASHBOARD: ${{secrets.GRAFANA_GITHUB_ACTION_DASHBAORD_LINK}}
        ESTIMATED_EXECUTION_TIME: 3600

    - name: Upload Dashboard Link
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.workflow}}-Dashboard
        path: |
          ${{github.workspace}}/Dashboard.html

  Coverage_Test:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: VM
    timeout-minutes: 5000
    steps:
    
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: | 
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}} -c --with-fpic 

    - name: Setup Monitoring Stack
      uses: ./.github/actions/setup-monitoring-stack
      with:
        GA_DETAIL: "NULL"

        POS_EXPORTER_PORT: ${{secrets.POS_EXPORTER_PORT}}

        AMP_REMOTE_WRITE_URL: ${{secrets.AMP_REMOTE_WRITE_URL}}
        AMP_SIGV4_REGION: ${{secrets.AMP_SIGV4_REGION}}
        AMP_SIGV4_ACCESS_KEY: ${{secrets.AMP_SIGV4_ACCESS_KEY}}
        AMP_SIGV4_SECRET_KEY: ${{secrets.AMP_SIGV4_SECRET_KEY}}

        LOGSTASH_PORT: ${{secrets.LOGSTASH_PORT}}

        OS_DOMAIN_ENDPOINT: ${{secrets.OS_DOMAIN_ENDPOINT}}
        OS_REGION: ${{secrets.OS_REGION}}

    - name: Build UT and Run
      id: build_ut_and_run
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/ut_build_run_coverage.sh
        .github/workflows/script/unit/ut_build_run_coverage.sh ${{github.workspace}}

    - name: Volume Test
      id: volume_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/volume/volume.sh
        .github/workflows/script/volume/volume.sh ${{github.workspace}}

    - name: Normal IO Test
      id: normal_io_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/normal_io.sh
        .github/workflows/script/normal_io_npor_spor/normal_io.sh ${{github.workspace}}

    - name: NPOR Test
      id: npor_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/npor.sh
        .github/workflows/script/normal_io_npor_spor/npor.sh ${{github.workspace}}

    - name: Rebuild Test
      id: rebuild_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/rebuild/rebuild.sh
        .github/workflows/script/rebuild/rebuild.sh ${{github.workspace}}

    - name: SPOR Test
      id: spor_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/spor_postcommit.sh
        .github/workflows/script/normal_io_npor_spor/spor_postcommit.sh ${{github.workspace}}

    - name: WBT Command Test
      id: wbt_command_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/wb_io_st/wbt_command_coverage.sh
        .github/workflows/script/wb_io_st/wbt_command_coverage.sh ${{github.workspace}}

    - name: Qos Test 
      id: qos_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/qos/qos.sh
        .github/workflows/script/qos/qos.sh ${{github.workspace}} VM

    - name: NVMe Flush Test
      id: nvme_flush_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/nvme_flush/nvme_flush.sh
        .github/workflows/script/nvme_flush/nvme_flush.sh ${{github.workspace}}

    - name: GC vm test
      id: gc_vm_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/gc_vm/gc_vm.sh
        .github/workflows/script/gc_vm/gc_vm.sh ${{github.workspace}}

    - name: SRM Test
      id: srm_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/srm/srm.sh
        .github/workflows/script/srm/srm.sh ${{github.workspace}}

    - name: Various Configuration Test
      id: various_configuration_test
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/various_config.sh
        .github/workflows/script/various_config.sh ${{github.workspace}}

    - name: Calculate Code Coverage for UT/IT/ST
      id: calculate_code_coverage_for_ut_it_st
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/code_coverage.sh
        .github/workflows/script/code_coverage.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Coverage_LOG
        path: |
          /var/log/pos